[package]
name = "wordle-solver"
version = "0.1.0"
edition = "2021"
authors = ["AlphaKeks <alphakeks@dawn.sh>"]

[profile.release]
debug = true

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.3"

clap = { version = "4", features = ["derive"] }

itertools = "0.10"

once_cell = "1.17"
