[package]
name = "wordle-solver"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
clap = { version = "4", features = ["derive"] }
itertools = "0.10"
tracing = "0.1"
tracing-subscriber = "0.3"
