[package]
name = "solver-cli"
version = "0.1.0"
edition = "2021"
authors = ["AlphaKeks <alphakeks@dawn.sh>"]

[dependencies]
tracing = { workspace = true }
tracing-subscriber = "0.3.17"
time = "0.3.21"
clap = { version = "4.3.0", features = ["derive"] }
