[package]
name = "solver-cli"
version = "0.1.0"
edition = "2021"
authors = ["AlphaKeks <alphakeks@dawn.sh>"]

[dependencies]
wordle = { path = "../wordle" }
tracing = { workspace = true }
tracing-subscriber = "0.3.17"
clap = { version = "4.3.0", features = ["derive"] }

